---
title: "funding_NIMH_plot"
# author: "Emtiaz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(scales)
library(zoo)
library(ggpubr)
library(latex2exp)
```

### Read all files
#### Step 1: Read NIMH emo vs nonEmo file

```{r echo=FALSE, warning=FALSE, message=FALSE}
df_NIMH = read.csv("Data/NIMH_emoVSnonemo.csv",stringsAsFactors = FALSE)
df_NIMH
```

#### Step 2: select specific columns; convert data types
```{r echo=FALSE, warning=FALSE, message=FALSE}
df_NIMH = df_NIMH %>% select(year, yFUND_emo_2018, fundPercentage)

df_NIMH$year = as.integer(df_NIMH$year)
df_NIMH$yFUND_emo_2018 = as.double(df_NIMH$yFUND_emo_2018)
df_NIMH$fundPercentage = as.double(df_NIMH$fundPercentage)

df_NIMH
```
#### Step 3: Filter NIMH year from 1985-2018;
```{r echo=FALSE, warning=FALSE, message=FALSE}
df_NIMH = df_NIMH %>% filter(year >= 1985 & year <= 2018)
df_NIMH
```

#### Step 4: Draw line plot for NIMH

```{r echo=FALSE, warning=FALSE, message=FALSE}
cols <- c("Adjusted(2018 US dollars)-NIMH"="green4")
lines <-  c("Adjusted(2018 US dollars)-NIMH" = 1)

g1 = ggplot(df_NIMH) + 
  geom_line(aes(x=year, y=yFUND_emo_2018/10^6, color = "Adjusted(2018 US dollars)-NIMH", linetype = "Adjusted(2018 US dollars)-NIMH"), size = 1.5, alpha = 0.8) +
  scale_x_continuous(breaks = seq(1985,2018,by=3), limits = c(1985,2018))+
  scale_y_continuous(breaks = seq(0,300,by=50), limits = c(0,300))+
  theme_bw()+
  theme(panel.grid.major = element_blank())+
  labs(x="", y="US dollars [M]", title = "Funding on Affective Research")+
  scale_linetype_manual(name = "",values = lines)+
  scale_color_manual(name="", values= cols)+
  theme(legend.key = element_rect(size=6),
        axis.text=element_text(size=12, face="bold"),
        axis.title=element_text(size=14,face="bold"),
        legend.position = "none",
        axis.title.y = element_text(margin=margin(t=0,r=10,b=0,l=0)),
        axis.title.x = element_text(margin=margin(t=10,r=0,b=0,l=0)),
        plot.margin = unit(c(0.3, 0.3, 0.3, 0.3), "cm"),
        plot.title = element_text(hjust = 0.5, size = 16, face="bold"))

g1
```

#### Step 5: Run Regression on NIMH 

```{r echo=FALSE, warning=FALSE, message=FALSE}
model_NIMH = lm(fundPercentage ~ year, data = df_NIMH)
summary(model_NIMH)


## get the p value
pStars_NIMH <- summary(model_NIMH)$coefficients[,"Pr(>|t|)"][[2]]
pStars_NIMH = format(round(pStars_NIMH, 3), nsmall = 3)
## get the r/estimate value
r_val_NIMH <- summary(model_NIMH)$coefficients[,"Estimate"][[2]] 
r_val_NIMH = format(round(r_val_NIMH, 3), nsmall = 3)
```

#### Step 6: Draw Regression plot

```{r echo=FALSE, warning=FALSE, message=FALSE}
r_val_NIMH
pStars_NIMH
annotation_text_model_NIMH = paste0("$\\textit{p < 0.001}$, $\\textit{r = ", r_val_NIMH,"$}")

cols <- c("Adjusted(2018 US dollars)-NIMH"="red")
lines <-  c("Adjusted(2018 US dollars)-NIMH" = 1)


g3 = ggplot(df_NIMH, aes(x=year, y=fundPercentage)) +
  geom_point(color = "red")+
  geom_smooth(method = "lm", se= FALSE, color="black")+
  scale_x_continuous(breaks = seq(1985,2018,by=3), limits = c(1985,2018))+
  theme_bw()+
  theme(panel.grid.major = element_blank(),
        axis.text=element_text(size=12, face="bold"),
        axis.title=element_text(size=14,face="bold"),
        legend.position = "none",
        axis.title.y = element_text(margin=margin(t=0,r=10,b=0,l=0)),
        axis.title.x = element_text(margin=margin(t=10,r=0,b=0,l=0)),
        plot.margin = unit(c(0.3, 0.5, 0.3, 0.5), "cm"),
        plot.title = element_text(hjust = 0.5, size = 16, face="bold"))+
  labs(x="", y="Budget Portion [%]", title = "Budget Portion on Affective Research")+
  annotate("text", x = 2012, y = 15, label = TeX(annotation_text_model_NIMH), fontface = 'italic', size=6) +
  scale_y_continuous(breaks = seq(0,15, by = 3), limits = c(0,15))


g3
```


#### Step 7: Draw final Combined plot 
```{r echo=FALSE, warning=FALSE, message=FALSE}
g_NIMH <- ggarrange(g1,g3,
                    labels = c("a", "b"),
                    font.label = list(size=20),
                    ncol=2,nrow=1)
g_NIMH
ggsave(paste0("Plots/NIMH_Plot.png"), g_NIMH, height = 5, width = 16)

```


























