---
title: "yearly_publication_PubMed"
# author: "Emtiaz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(scales)
library(zoo)
library(ggpubr)
library(latex2exp)
```

### Read all files and set the data types
```{r echo=FALSE, warning=FALSE, message=FALSE}
df_emotion_pubmed = read.csv("Data/timeline_Emotions.csv",stringsAsFactors = FALSE)
df_behavior_pubmed = read.csv("Data/timeline_behavior.csv",stringsAsFactors = FALSE)

df_emotion_pubmed$year = as.integer(df_emotion_pubmed$year)
df_emotion_pubmed$count = as.integer(df_emotion_pubmed$count)
df_emotion_pubmed

df_behavior_pubmed$year = as.integer(df_behavior_pubmed$year)
df_behavior_pubmed$count = as.integer(df_behavior_pubmed$count)
df_behavior_pubmed

```

### Filter year from 1980 to 2018
```{r echo=FALSE, warning=FALSE, message=FALSE}

df_emotion_pubmed = df_emotion_pubmed %>% filter(year >= 1980 & year<=2018)
df_emotion_pubmed

df_behavior_pubmed = df_behavior_pubmed %>% filter(year >= 1980 & year<=2018)
df_behavior_pubmed



```

### Rename column names and join them together
```{r echo=FALSE, warning=FALSE, message=FALSE}
colnames(df_emotion_pubmed) <- c('year', 'emotion_count')

df_yearly = df_emotion_pubmed %>% merge(df_behavior_pubmed, by ='year')
df_yearly
```

### Calculate the percentages
```{r echo=FALSE, warning=FALSE, message=FALSE}
df_yearly = df_yearly %>% mutate(emoPercent = emotion_count * 100 / count)
df_yearly
```


### Draw the Yearly publication plot
```{r echo=FALSE, warning=FALSE, message=FALSE}
p = ggplot(df_yearly, aes(x=year, y=emotion_count)) +
  geom_bar(stat = "identity", fill="dodgerblue", alpha= 0.8) +
  coord_cartesian(xlim = c(1980,2018)) +
  scale_x_continuous(breaks = seq(1980,2018,by=4)) +
  scale_y_continuous(breaks = seq(0,8000,by=2000), limits = c(0,8000)) +
  theme_bw()+
  theme(panel.grid.major = element_blank(),
        axis.text=element_text(size=14, face="bold"),
        axis.title=element_text(size=16,face="bold"),
        legend.position = "none",
        axis.title.y = element_text(margin=margin(t=0,r=10,b=0,l=0)),
        axis.title.x = element_text(margin=margin(t=10,r=0,b=0,l=0))) +
  labs(x="", y="# Publications - MeSH: Emotions", title = "")
  
p


```


#### Regression on PubMed data
```{r echo=FALSE, warning=FALSE, message=FALSE}
model = lm(emoPercent ~ year, data = df_yearly)
summary(model)


## get the p value
pStars <- summary(model)$coefficients[,"Pr(>|t|)"][[2]]
pStars = format(round(pStars, 3), nsmall = 3)
pStars
## get the r/estimate value
r_val <- summary(model)$adj.r.squared 
r_val = format(round(r_val, 3), nsmall = 3)
r_val

```

#### Draw Plot
```{r echo=FALSE, warning=FALSE, message=FALSE}

annotation_text_model = paste0("$\\textit{p < 0.001}$, $\\textit{r = ", r_val,"}$")

g = ggplot(df_yearly, aes(x=year, y=emoPercent)) +
  geom_point(color = "red")+
  geom_smooth(method = "lm", se= FALSE, col='black')+
  scale_x_continuous(breaks = seq(1980,2018,by=4), limits = c(1980,2018))+
  theme_bw()+
  theme(panel.grid.major = element_blank(),
        axis.text=element_text(size=14, face="bold"),
        axis.title=element_text(size=16,face="bold"),
        legend.position = "none",
        axis.title.y = element_text(margin=margin(t=0,r=10,b=0,l=0)),
        axis.title.x = element_text(margin=margin(t=10,r=0,b=0,l=0)),
        plot.margin = unit(c(0.3, 0.5, 0.3, 0.5), "cm"))+
  labs(x="", y="% Publications - MeSH: Emotions in Behavior", title = "")+
  annotate("text", x = 2012, y = 10, label = TeX(annotation_text_model), fontface = 'italic', size=6) +
  scale_y_continuous(breaks = seq(0,10, by = 2), limits = c(0,10))

g

```

### Save the plot
```{r echo=FALSE, warning=FALSE, message=FALSE}

g_final2 <- ggarrange(p, g,
                     labels = c("a", "b"),
                     ncol = 2, nrow = 1,
                     font.label = list(size=24))
print(g_final2)
ggsave(paste0("Plots/pubMedyearlyPlot.png"), g_final2, height = 7, width = 18)
```





